### ISSUE TITLE
HU6: Authenticate User

### ISSUE THREAD

**Issue by acalvom** [acalvom/tfm-management#5]
As an user, I want to login and logout in the application to access to the options menu according to my role.
- [x] Create the login/logout menu and the JWT management
- [x] Create the end-point and assign the privileges to a certain role
- [x] Create the resource in the database, add manually the three types of user to verify the functioning

**Comment by acalvom** [comment]
**TASKS**
- Create the Angular component for "Login" and the navigation bar with Angular Material - `FRONT-END`
- Create the Angular service for "Login" - `FRONT-END`
- Implement the NodeJS end-point for "Login" - `BACK-END`
- Install "crypto-js" to encrypt the password in the body and implement the encryption/decryption - `FRONT-END` `BACK-END` 
- Create 'users' table in the database and add three types of users (admin, teacher and student) - `DATABASE`
- Implement the query to verify the user credentials and role and validate the application connection - `FRONT-END` `BACK-END` `DATABASE`
- Install "jsonwebtoken" and implement the functionalities: generate token, set token and role in headers  `BACK-END`
- Implement the token validation and role assignement - `FRONT-END` `BACK-END`
- Add "Logout" and "Home" redirection after login - `FRONT-END`
- Implement NodeJS tests for "Login" and "Middleware" - `BACK-END`
- Refactor code - `FRONT-END` `BACK-END`
- Fix SonarCloud issues - `FRONT-END` `BACK-END`
