### ISSUE TITLE
HU1: Create User

### ISSUE THREAD

**Issue by acalvom** [acalvom/tfm-management#6]
As an admin user, I want to add new users in the application to to create teachers and students
- [x] Create the register menu and the form with the proper fields and validation
- [x] Create the service in Angular to create new users [POST]
- [x] Create the end-point to create new users [POST]

**Comment by acalvom** [comment]
**TASKS**
- Create the Angular component for "Resgister" and with Angular Material - `FRONT-END`
- Create the Angular service for "Resgister" - `FRONT-END`
- Implement the NodeJS end-point for "Resgister" - `BACK-END`
- Install "bcrypt" to encrypt the password in the database and implement the encryption/decryption - `BACK-END`
- Implement the query to register a new user and assert that only 'admin' user can create new users - `BACK-END`
- Set the token in the client requests with the role - `FRONT-END`
- Implement NodeJS tests for "Resgister" - `BACK-END`
- Refactor "Login" tests to apply new changes - `BACK-END`
- Fix SonarCloud issues - `BACK-END`
